apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v2
  template:
    metadata:
      labels:
        app: payment
        version: v2
    spec:
      containers:
        - name: app
          image: payment:v2
          ports:
            - containerPort: 8080

