apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      containers:
        - name: app
          image: payment:v1
          ports:
            - containerPort: 8080

